version: '3.8'

services:
  web:
    container_name: onetime_message_creator
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /opt/django-apps/data/onetime_message_creator:/app/db
    ports:
      - "10101:8000"
    user: "www-data"
