# Generated by Django 4.0.5 on 2022-11-23 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20, verbose_name='Geschlecht')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AdditionalUserInfos',
            },
        ),
    ]
