# Generated by Django 4.1.7 on 2023-07-13 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnetimePassword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Bezeichnung"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Benutzername",
                    ),
                ),
                ("password", models.CharField(max_length=256, verbose_name="Passwort")),
                (
                    "name_of_opener",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Öffner"
                    ),
                ),
                (
                    "one_time_token",
                    models.CharField(max_length=256, verbose_name="Einmal-Token"),
                ),
                (
                    "token_expiry_date",
                    models.DateTimeField(verbose_name="Token Ablauf Datum"),
                ),
                ("opend", models.BooleanField(verbose_name="Geöffnet?")),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "OnetimePasswords",
            },
        ),
        migrations.CreateModel(
            name="OnetimeMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Bezeichnung"
                    ),
                ),
                ("message", models.TextField(default="", verbose_name="Nachricht")),
                (
                    "name_of_opener",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Öffner"
                    ),
                ),
                (
                    "one_time_token",
                    models.CharField(max_length=256, verbose_name="Einmal-Token"),
                ),
                (
                    "token_expiry_date",
                    models.DateTimeField(verbose_name="Token Ablauf Datum"),
                ),
                ("opend", models.BooleanField(verbose_name="Geöffnet?")),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "OnetimeMessages",
            },
        ),
    ]
