# Generated by Django 4.1.7 on 2023-07-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_onetimepassword_onetimemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="token_expiry_date",
            field=models.DateField(verbose_name="Token Ablauf Datum"),
        ),
    ]
