# Generated by Django 4.1.7 on 2023-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_onetimepassword_token_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="opend",
            field=models.BooleanField(default=False, verbose_name="Geöffnet?"),
        ),
    ]
