# Generated by Django 4.1.7 on 2023-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_onetimepassword_opend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimemessage",
            name="opend",
            field=models.BooleanField(default=False, verbose_name="Geöffnet?"),
        ),
    ]
