# Generated by Django 4.1.7 on 2023-07-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_onetimemessage_opend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimemessage",
            name="token_expiry_date",
            field=models.DateField(verbose_name="Token Ablauf Datum"),
        ),
    ]
