# Generated by Django 4.2.3 on 2023-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_onetimemessage_token_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimemessage",
            name="open_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Öffnungsdatum"
            ),
        ),
        migrations.AddField(
            model_name="onetimepassword",
            name="open_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Öffnungsdatum"
            ),
        ),
    ]
