# Generated by Django 4.2.3 on 2023-08-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_onetimemessage_open_date_onetimepassword_open_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSetting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email_user_name",
                    models.CharField(max_length=50, verbose_name="Email-Absender-Name"),
                ),
                (
                    "email_user",
                    models.EmailField(max_length=254, verbose_name="Email-Absender"),
                ),
                (
                    "email_password",
                    models.CharField(
                        max_length=256, verbose_name="Email-Absender-Passwort"
                    ),
                ),
                (
                    "name_error_reciever",
                    models.CharField(
                        max_length=50, verbose_name="Email-ErrorEmpfaenger-Name"
                    ),
                ),
                (
                    "email_error_receiver",
                    models.EmailField(
                        max_length=254, verbose_name="Email-ErrorEmpfaenger"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
            ],
            options={
                "verbose_name_plural": "AdminSettings",
            },
        ),
        migrations.CreateModel(
            name="Sended_Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "receiver_mail",
                    models.CharField(
                        max_length=200, verbose_name="Empfänger-Mailadresse"
                    ),
                ),
                (
                    "sender_mail",
                    models.CharField(max_length=200, verbose_name="Sender-Mailadresse"),
                ),
                ("content", models.TextField(verbose_name="Inhalt")),
                ("subject", models.CharField(max_length=200, verbose_name="Betreff")),
                (
                    "error_massage",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error-Nachricht"
                    ),
                ),
                ("send_status", models.BooleanField(verbose_name="Gesendet")),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt"),
                ),
            ],
            options={
                "verbose_name_plural": "Sended_Emails",
            },
        ),
        migrations.AddField(
            model_name="additionaluserinfo",
            name="has_loged_in",
            field=models.BooleanField(default=False, verbose_name="War eingeloggt?"),
        ),
        migrations.AddField(
            model_name="additionaluserinfo",
            name="one_time_token",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Einmal-Token"
            ),
        ),
        migrations.AddField(
            model_name="additionaluserinfo",
            name="token_expiry_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Token Ablauf Datum"
            ),
        ),
    ]
